spring:
  application:
    name: spring-boot-rest-testing
  profiles:
    active: production
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useTimeZone=true&serverTimeZone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none #update
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true

---
# Production #
spring:
  config:
    activate:
      on-profile: production
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useTimeZone=true&serverTimeZone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
     ddl-auto: none #update
    show-sql: false
    properties:
      hibernate:
       '[format_sql]': false
    #open-in-view: false
